### PR TITLE
chore: add info about the Matrix community chat channel

### PR DESCRIPTION
**Pull request by JohnVillalovos**

### CODE REVIEW

**Review by StykMartin — APPROVED** [review]

**Comment by nforro** [comment]
@JohnVillalovos It turns out it is a known limitation of Packit, we have updated the [docs](https://packit.dev/docs/configuration/upstream/copr_build#optional-parameters) to make it more clear. To avoid this, you have to set a different `identifier` option for each `copr_build` job, then the status check updates will be done independently for each of them and should be always up-to-date.
I've also noticed you are still using the `metadata` key your Packit config; it has been deprecated long ago and you can safely drop it.

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos It turns out it is a known limitation of Packit, we have updated the [docs](https://packit.dev/docs/configuration/upstream/copr_build#optional-parameters) to make it more clear. To avoid this, you have to set a different `identifier` option for each `copr_build` job; then the status check updates will be done independently for each of them and should be always up-to-date. I've also noticed you are still using the `metadata` key in your Packit config; it has been deprecated long ago and you can safely drop it.

Thanks @nforro  I have created a PR to do what you suggested.   https://github.com/beaker-project/beaker/pull/224

That PR passed CI. So hopefully that is the fix. I say hopefully because other PRs have passed before.

Thanks again.

**Pull request merged**
