### PR TITLE
Do not modify /boot/efi/EFI/redhat/grub.cfg on unified grub.cfg setup

### PR DESCRIPTION
**Pull request by nomuranec**
This resolves the issue https://github.com/beaker-project/beaker/issues/147

The method to check if the system is unified grub.cfg setup follows scriptlet from grub2-common package.

Signed-off-by: Jun'ichi Nomura <junichi.nomura@nec.com>

### CODE REVIEW

**Comment by nomuranec** [comment]
Reference to the grub2 rpm scriptlet
https://gitlab.com/redhat/centos-stream/rpms/grub2/-/blob/575027c3e43311c25cbd5565d2b114c43669594e/grub2.spec#L329

**Review by StykMartin — APPROVED** [review]
LGTM. Thanks @nomuranec

**Comment by StykMartin** [comment]
@nomuranec Did you change your template in NEC and we keep this in develop branch or do you need a new release? If a new release is needed I will cherry-pick it to release-28 and create a new release as well.

**Comment by nomuranec** [comment]
@StykMartin I have changed my template.  So it's ok to keep this in develop branch.

**Comment by StykMartin** [comment]
Ok. Thank you for the patch @nomuranec!

**Pull request merged**
