### PR TITLE
read client configuration from both user config file and system

### PR DESCRIPTION
**Pull request by qhsong**
Bugzilla – Bug 844364

### CODE REVIEW

**Comment by danc86** [comment]
Thanks for the patch @qhsong!

Can you please just amend it to take out all the unrelated whitespace changes?

We will also need to add a test case for this functionality, would you like to have a go at writing it? See `IntegrationTests/src/bkr/inttest/client`.

BTW we normally accept patches on [our Gerrit instance](https://gerrit.beaker-project.org/), not Github, but if you don't feel like setting up an account on Gerrit I can just submit the patch for you.

**Comment by qhsong** [comment]
Ok, I will fixed it.
I try to use gerrit to submit my code, but it tells me I can not access to this repo although I have add my ssh key to it. It is so wired, so would you pls help me to submit a patch for me?

**Comment by danc86** [comment]
Did you set a username in Gerrit? It is blank by default, which means when you are SSH'ing to Gerrit to upload your patch Gerrit doesn't know who you are.

**Comment by danc86** [comment]
But yes, if you prefer to post the patch here I can easily upload it to Gerrit for you. Your choice.

**Comment by qhsong** [comment]
I have add test and success add as review in gerrit `https://gerrit.beaker-project.org/#/c/5175/`. Would you help me to review this code and add other to it?

**Comment by danc86** [comment]
Thanks @qhsong, let's continue the discussion on Gerrit.

**Pull request closed without merging**
