### PR TITLE
CI Playground 

### PR DESCRIPTION
**Pull request by StykMartin**
This is just testing PR to see if GitHub Actions are working properly (again).

### CODE REVIEW

**Comment by TomasTomecek** [comment]
WOOOOOOOT! all :green_book:

**Comment by StykMartin** [comment]
@danrodrig @cbouchar @renanrodrigo take a look. Everything seems to be fine.

We have the following:
- Dogfood executed in our development env
- RHEL 7 build created by our build system. The same build system is producing production artifacts
- Pylint checks
- Documentation checks
- Upstream first COPR builds

**Comment by StykMartin** [comment]
/:eyes:

**Pull request closed without merging**
