### PR TITLE
Add a bkr loan-request command

### PR DESCRIPTION
**Pull request by skycastlelily**
This PR fixes https://github.com/beaker-project/beaker/issues/72

### CODE REVIEW

**Comment by skycastlelily** [comment]
I have tested the code by manually add the file to /usr/lib/xxxx dir,and load-request is sent successfully after I run "bkr loan-request $fqdn"

**Comment by JohnVillalovos** [comment]
Is it bk-loaD or bkr-loaN ?

Title says 'load' while content talks about 'loan'

**Comment by skycastlelily** [comment]
> Is it bk-loaD or bkr-loaN ?
> 
> Title says 'load' while content talks about 'loan'

Ah,sorry, it's a typo,should be loan,thanks for potting it out,and I modified it just now.

**Comment by renanrodrigo** [comment]
Hello, @skycastlelily 
First of all, thanks for the PR.
It will be dealt with as soon as possible, given the team's current constraints.

**Comment by skycastlelily** [comment]
Hi Renan,

Thanks for letting me know.

**Comment by StykMartin** [comment]
Hi, @skycastlelily.

I wonder if this is something that you need for Red Hat Instance of Beaker or Upstream Beaker.
The client is now separated. If this patch should be incorporated into the RH instance, please reach out to RH BKR maintainers.

**Comment by StykMartin** [comment]
I merged this one to the upstream version, however, it will not downstream client.

**Comment by skycastlelily** [comment]
Thanks Martin,I'm gonna to contact the RH BKR maintainers.

**Pull request merged**
