### PR TITLE
Add multi-console log support

### PR DESCRIPTION
**Pull request by jvillal-amp**
Support console files with the name of $CONSOLE_LOGS/$FQDN*

For example:
  If CONSOLE_LOGS=/var/consoles and the FQDN=test.example.com

  Then the following files will be logged as console files:
    /var/consoles/test.example.com -> console.log
    /var/consoles/test.example.com-bmc -> console-bmc.log
    /var/consoles/test.example.com-serial2 -> console-serial2.log

Bug: 1771666
Change-Id: I6c5cac2b1eb97b6d7d98ff6adb4dbc27509aa862

### CODE REVIEW

**Comment by JohnVillalovos** [comment]
> 
> 
> All green @jvillal-amp impressive. However, this patch should go into release-27 branch.
> We can release it faster (a lot faster).

Thanks Martin. I have created a new pull request: https://github.com/beaker-project/beaker/pull/11 against the release-27 branch.

**Comment by StykMartin** [comment]
Yeah this is dead. Let's use #11

**Pull request closed without merging**
